version: '3.9'

services:
  api:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      - WATCHFILES_FORCE_POLLING=true
